# See https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/integrations/intellij/soar-ide"
    update_schedule: "daily"
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
